from adsigno.process import process

from adsigno.solution_report import solution_report
from adsigno.solution_report import make_gtables
from adsigno.solution_report_admin import solution_report_4_admin